### ISSUE TITLE
Anything, and especially its "Animated SVG" example from the demo, is confusing.

### ISSUE THREAD

**Issue by dabrahams** [rajgoel/reveal.js-demos#13] opened 2021-10-10 17:39 UTC
Because the example slides don't show any of the code needed to set it up or even hint at the relevant class name (`animate`), it's unclear what the plugin is doing.  It took me literally an hour to discover what was happening… turns out it's all in the initialization options for anything at the bottom of the file, which aren't cited in the deck.  

I have honestly been unclear on what this plugin actually does for weeks.  Now that I (think) I understand it, I'd have named it “ad hoc,” with no negative connotation intended: it basically lets you add new plugins on an ad-hoc basis, inside your reveal.js initialization.

One thing that's still unclear to me: why would I want to do that, rather than building a first-class plugin in a separate file?  I can understand it for some of the very short examples, I guess, but many of the examples don't seem to benefit by being ad-hoc.

I'm not sure exactly what changes to suggest at the moment, but would be happy to try to improve the documentation and demo a bit, if you're interested.

**Comment by dabrahams** [comment] 2021-10-10 17:46
Oh, another confusing point: why does that example exist in the same repository with the animate plugin, which seems to have the same basic purpose?

**Comment by rajgoel** [comment] 2021-10-10 18:13
Sorry, but the code needed for the demos is found in the source code of the demos and, so far, the demos are not meant to be tutorials. I appreciate your feedback, but in this case it isn't very constructive. `anything` and `animate` plugins have different use cases and purposes. If you don't have a use for the `anything` plugin, you can just ignore it. For me it is particularly useful for rapid prototyping.

**Comment by rajgoel** [comment] 2021-10-10 18:14
Duplicate of https://github.com/rajgoel/reveal.js-plugins/issues/127

**Closed as completed by rajgoel** 2021-10-10 18:14 UTC

**Comment by dabrahams** [comment] 2021-10-11 00:14
> I appreciate your feedback, but in this case it isn't very constructive. 

Sorry about that, let me try to remedy that problem.

> anything and animate plugins have different use cases and purposes. If you don't have a use for the anything plugin, you can just ignore it. For me it is particularly useful for rapid prototyping.

Yes!  You see, the problem for me was that it took me a few weeks of puzzling over the plugin on and off before I realized that “quick prototyping” (i.e. ad-hoc-ness) what it was really bringing to the table.  Why did I give it so much attention? If you can put yourself in my shoes for a moment, I'm just discovering reveal.js, and I find this plugin called “anything,” at the very top of the preeminent entry in the reveal.js third-party plugin list, and the demo seems to show it doing this very broad variety of things, so it looks incredibly powerful… and I'm trying to figure out what those things have in common.  It turns out, not much; all the real power is in how the user sets it up, but the way the plugin is presented, that isn't very obvious to the new observer. At least, it wasn't to me, and I generally assume someone else is going to have the same problem.  I'd like to offer some edits to the description and/or demo that would make clear the overall intended use (quick prototyping) and intended audience (users who want to trigger some arbitrary JS, e.g. hackers, rather than just those capable of reproducing some documented options syntax) of this plugin. But if you are not receptive to such PRs, I won't waste any more of your time.  Just LMK.

Thanks again,
Dave

**Comment by rajgoel** [comment] 2021-10-11 08:37
I'd say the best place to contribute at the moment would be improving the documentation in the [Readme](https://github.com/rajgoel/reveal.js-plugins/blob/master/anything/README.md) file.
